import mAnimation from "./m-animation/m-animation.vue";
import mButton from "./m-button/m-button.vue";
import mCascader from "./m-cascader/m-cascader.vue";
import mCheckbox from "./m-checkbox/m-checkbox.vue";
import mDialog from "./m-dialog/m-dialog.vue";
import mEditor from "./m-editor/m-editor.vue";
import mFile from "./m-file/m-file.vue";
import mFileV2 from "./m-file-v2/m-file-v2.vue";
import mForm from "./m-form/m-form.vue";
import mFormV2 from "./m-form-v2/m-form-v2.vue";
import mIcon from "./m-icon/m-icon.vue";
import mIconV2 from "./m-icon-v2/m-icon-v2.vue";
import mInput from "./m-input/m-input.vue";
import mInputV2 from "./m-input-v2/m-input-v2.vue";
import mLineMap from "./m-line-map/m-line-map.vue";
import mMediaView from "./m-media-view/m-media-view.vue";
import mMediaVisible from "./m-media-view/m-media-visible.vue";
import mNumber from "./m-number/m-number.vue";
import mNumberV2 from "./m-number-v2/m-number-v2.vue";
import mRadio from "./m-radio/m-radio.vue";
import mScrollBar from "./m-scrollbar/m-scrollbar.vue";
import mScrollBarV2 from "./m-scrollbar-v2/m-scrollbar-v2.vue";
import mScrollBarList from "./m-scrollbar-list/m-scrollbar-list.vue";
import mSelect from "./m-select/m-select.vue";
import mSwitch from "./m-switch/m-switch.vue";
import MTable from "./m-table/m-table.vue";
import mTabs from "./m-tabs/m-tabs.vue";
import mTabItem from "./m-tabs/m-tab-item.vue";
import mTabsV2 from "./m-tabs-v2/m-tabs-v2.vue";
import MTabsV2Item from "./m-tabs-v2/m-tabs-v2-item.vue";
import mTime from "./m-time/m-time.vue";
import mTitle from "./m-title/m-title.vue";
import mTitleV2 from "./m-title-v2/m-title-v2.vue";
import mSelectV2 from "./m-select-v2/m-select-v2.vue";
import mPopoverV2 from "./m-popover-v2/m-popover-v2.vue";
import mTag from "./m-tag-v2/m-tag-v2.vue";
import MDrawerV2 from "./m-drawer-v2/m-drawer-v2.vue";
import mTimeV2 from "./m-time-v2/m-time-v2.vue";
import MOverlayV2 from "./m-overlay-v2/m-overlay-v2.vue";
import MTableV2 from "./m-table-v2/m-table-v2.vue";
import mCheckboxV2 from "./m-checkbox-v2/m-checkbox-v2.vue";
import MCheckboxV2Item from "./m-checkbox-v2/m-checkbox-v2-item.vue";
import mRadioV2 from "./m-radio-v2/m-radio-v2.vue";
import MRadioV2Item from "./m-radio-v2/m-radio-v2-item.vue";
import mSwitchV2 from "./m-switch-v2/m-switch-v2.vue";
import MPaginationV2 from "./m-pagination-v2/m-pagination-v2.vue";
import MCascaderV2 from "./m-cascader-v2/m-cascader-v2.vue";
import MRowV2 from "./m-row-v2/m-row-v2.vue";
import MColV2 from "./m-col-v2/m-col-v2.vue";
import MSelectIconV2 from "./m-select-icon-v2/m-select-icon-v2.vue";
import MTransferV2 from "./m-transfer-v2/m-transfer-v2.vue";

declare module "vue" {
  interface GlobalComponents {
    mAnimation: typeof mAnimation;
    mButton: typeof mButton;
    mCascader: typeof mCascader;
    mCheckbox: typeof mCheckbox;
    mCheckboxV2: typeof mCheckboxV2;
    MCheckboxV2Item: typeof MCheckboxV2Item;
    mRadioV2: typeof mRadioV2;
    MRadioV2Item: typeof MRadioV2Item;
    mDialog: typeof mDialog;
    mEditor: typeof mEditor;
    mFile: typeof mFile;
    mFileV2: typeof mFileV2;
    mForm: typeof mForm;
    mFormV2: typeof mFormV2;
    MDrawerV2: typeof MDrawerV2;
    mIcon: typeof mIcon;
    mIconV2: typeof mIconV2;
    mInput: typeof mInput;
    mInputV2: typeof mInputV2;
    mLineMap: typeof mLineMap;
    mMediaView: typeof mMediaView;
    mMediaVisible: typeof mMediaVisible;
    mNumber: typeof mNumber;
    mNumberV2: typeof mNumberV2;
    mRadio: typeof mRadio;
    mScrollBar: typeof mScrollBar;
    mScrollBarV2: typeof mScrollBarV2;
    mScrollBarList: typeof mScrollBarList;
    mSelect: typeof mSelect;
    mSelectV2: typeof mSelectV2;
    mSwitch: typeof mSwitch;
    mTable: typeof MTable;
    mTabs: typeof mTabs;
    mTabItem: typeof mTabItem;
    mTabsV2: typeof mTabsV2;
    MTabsV2Item: typeof MTabsV2Item;
    mTime: typeof mTime;
    mTitle: typeof mTitle;
    mTitleV2: typeof mTitleV2;
    mPopoverV2: typeof mPopoverV2;
    mTag: typeof mTag;
    mTimeV2: typeof mTimeV2;
    MOverlayV2: typeof MOverlayV2;
    MTableV2: typeof MTableV2;
    mSwitchV2: typeof mSwitchV2;
    MPaginationV2: typeof MPaginationV2;
    MCascaderV2: typeof MCascaderV2;
    MRowV2: typeof MRowV2;
    MColV2: typeof MColV2;
    MSelectIconV2: typeof MSelectIconV2;
    MTransferV2: typeof MTransferV2;
  }

  interface AppContext {
    app: App;
    config: AppConfig;
    mixins: ComponentOptions[];
    components: Record<string, Component>;
    directives: Record<string, Directive>;
    provides: Record<string | symbol, any>;
    globalMethod: {
      getManagerV2GlobalZIndex: () => number;
    };
  }
}
